"""Compatibility imports for flight providers and their existing helpers.

Implementation lives in providers/, separated by responsibility."""

from agentic_flights.providers.base import (
    Provider,
    ProviderError,
    ProviderResult,
)
from agentic_flights.providers.browser import (
    _RESULT_SELECTOR,
    BrowserProvider,
    _build_browser_query,
    _explore_complete_tickets,
    _load_source_labels,
    _mark_source_stop,
    _open_search_page,
    _result_labels,
    _search_discovery_browser,
    _select_label,
)
from agentic_flights.providers.fli import (
    FliProvider,
    _CapturingClient,
    _enum_code,
    _has_wrb_payload,
    _normalize_option,
)
from agentic_flights.providers.parsing import (
    _RESULT_RE,
    _baggage_meets_requirement,
    _choice_identity,
    _line_has_amount,
    _parse_baggage_allowance,
    _parse_browser_label,
    _parse_complete_itinerary,
    _parse_complete_round_trip,
    _parse_discovery_options,
    _parse_local_datetime,
    _parse_provider_final_total,
    _parse_selected_booking_option,
    _validate_booking_routes,
)
from agentic_flights.providers.traversal import (
    _BudgetExhausted,
    _complete_quote_key,
    _complete_result,
    _consume_transition,
    _continuation,
    _read_continuation,
    _record_branch_error,
    _run_bounded_exploration,
    _search_fingerprint,
)

__all__ = [
    "Provider",
    "ProviderError",
    "ProviderResult",
    "_RESULT_SELECTOR",
    "BrowserProvider",
    "_build_browser_query",
    "_explore_complete_tickets",
    "_load_source_labels",
    "_mark_source_stop",
    "_open_search_page",
    "_result_labels",
    "_search_discovery_browser",
    "_select_label",
    "FliProvider",
    "_CapturingClient",
    "_enum_code",
    "_has_wrb_payload",
    "_normalize_option",
    "_RESULT_RE",
    "_baggage_meets_requirement",
    "_choice_identity",
    "_line_has_amount",
    "_parse_baggage_allowance",
    "_parse_browser_label",
    "_parse_complete_itinerary",
    "_parse_complete_round_trip",
    "_parse_discovery_options",
    "_parse_local_datetime",
    "_parse_provider_final_total",
    "_parse_selected_booking_option",
    "_validate_booking_routes",
    "_BudgetExhausted",
    "_complete_quote_key",
    "_complete_result",
    "_consume_transition",
    "_continuation",
    "_read_continuation",
    "_record_branch_error",
    "_run_bounded_exploration",
    "_search_fingerprint",
]
